# Generated by Django 2.0.4 on 2018-04-26 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('area', models.PositiveIntegerField()),
                ('parking_spaces', models.PositiveIntegerField()),
                ('property_company', models.CharField(max_length=255)),
                ('property_costs', models.PositiveIntegerField()),
                ('heating_method', models.CharField(choices=[('concentrated', '集中供暖'), ('selfburning', '自烧锅炉')], default='concentrated', max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='app.City')),
            ],
            options={
                'db_table': 'house',
            },
        ),
    ]
